<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fiap.bank</groupId>
        <artifactId>fiap-bank-atm</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>presentation</artifactId>
    
    <dependencies>
    <!-- Mantém o acesso à camada de Aplicação -->
        <dependency>
            <groupId>com.fiap.bank</groupId>
            <artifactId>application</artifactId>
            <version>${project.version}</version>
        </dependency>

    <!-- Nova injeção do Banco em Memória apenas na hora de rodar -->
        <dependency>
            <groupId>com.fiap.bank</groupId>
            <artifactId>infrastructure</artifactId>
            <version>${project.version}</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <mainClass>com.fiap.bank.atm.presentation.AtmApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>