<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fiap.bank</groupId>
        <artifactId>fiap-bank-atm</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>presentation</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- Regra: Presentation enxerga APENAS application -->
        <dependency>
            <groupId>com.fiap.bank</groupId>
            <artifactId>application</artifactId>
        </dependency>
        
        <!-- Componente visual FlatLaf usado apenas na camada de telas -->
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- 3. CORREÇÃO: Plugin de inicialização configurado na camada correta (apresentação) -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <mainClass>com.fiap.bank.presentation.AtmApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
